version: "3.7"
services:
  api:
    build: api
    command: yarn start
    working_dir: /usr/app/
    hostname: vlsu-backend
    volumes:
      - ../../backend/:/usr/app/
    ports:
      - "3000:3000"
  front:
    build: front
    command: yarn start
    working_dir: /usr/app/
    hostname: vlsu-frontend
    volumes:
      - ../../frontend/:/usr/app/
    ports:
      - "3001:3000"
