version: "3.7"
services:
  api:
    build: api
    working_dir: /usr/app/
    hostname: vlsu-backend
    volumes:
      - ../../backend/:/usr/app/
    ports:
      - "3000:3000"
    links:
      - mongo
  front:
    build: front
    working_dir: /usr/app/
    hostname: vlsu-frontend
    volumes:
      - ../../frontend/:/usr/app/
    ports:
      - "4201:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - api
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db/datadir:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
